- src/commands/with-cache.yml
If true, includes current branch name to cache key
Sometimes we might need to not include branch name in the cache key. So a config available for that will be helpful.
There can be cases where users won't want to include the branch name in the cache key. Currently since cache key always has branch name there is no way this orb can be used for such case. So a new boolean parameter based on which branch name is added to cache key is introduced. By default its values is true so that the current behaviour is preserved.
> Add include-branch-in-cache-key parameter

- src/commands/with-cache.yml
Fix a bug with include-branch-in-cache-key parameter 
include-branch-in-cache-key parameter is not saving cache as branch is included in save_cache step
> fix include-branch-in-cache-key parameter bug

- src/commands/install-npm.yml
The latest version of Alpine Linux is v3.10: https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases
However, the regexp used in the `sed` command in `install-npm.yml` only supports single digit minor versions, e.g. it supports 3.9 but not 3.10.
This change updates the regexp used so that is also supports minor versions which are more than just one digit long.
> Support x.yy Alpine version numbers in install-npm.yml

- src/@orb.yml
- src/commands/npm-ci.yml
- src/jobs/run.yml
- src/jobs/test.yml
This was prompted by a conversation in slack, about how easy we could make onboarding a new NodeJS project.
* Adds `npm-ci`, which installs dependencies in the [way npm recommends for CI](https://docs.npmjs.com/cli/ci)
* Adds `run` job, which does checkout, dependencies, then runs whatever you tell it to
* Adds `test` job, which does checkout, dependencies, then runs your tests
> Add quickstart jobs with examples

- src/commands/install-packages.yml
Provide an exit 1 if no package.json is found.
Currently, a warning will be given but no error: https://app.circleci.com/pipelines/github/CircleCI-Public/serverless-framework-orb/82/workflows/2246dd64-714c-43b9-a339-a3c86a4009f1/jobs/219
> Error if no package.json file. [semver:patch]

- .circleci/config.yml
- src/commands/install.yml
- Fixes a bug fetching the  "latest" node version that could cause build failures.
- Most users will want the "lts" or "stable" version
- The current method of getting the latest Node.js is incorrect. The "latest" version currently fetched is the most recently updated, which is incorrect. At the time of this commit, the "latest" version on GitHub is 10.20.1, well behind the latest.
- Adds support for "lts" and "stable" as node-version parameters
This new method is based on tj/n's method of fetching versions:
https://github.com/tj/n/blob/8c55fba3d504a69e79946dfef1ad242c67f27552/bin/n#L960-L1019
tj/n references Node's own dist-indexer as a source:
https://github.com/nodejs/nodejs-dist-indexer/blob/master/dist-indexer.js
> Improving fetching of node versions [semver:minor]

- src/commands/install-packages.yml
I was unable to have the correct use of the `override-ci` option in the node/install-packages command.
After looking into the code, I detect a bug in the comparison used to detect if the "boolean" is true/false.
It's because, in bash, there is no boolean.
The current comparison is evaluate as a string.
So every time the script ran, the bash script think the `override-ci` value is `true` because there is some content.
> fix: use string comparison in bash code for "boolean" [semver:patch]

- src/examples/run_tests_with_npm.yml
It looks like the major version only tags aren't available for `cimg` on Dockerhub. This PR updates the two executor tags to include the latest minor release of Node 13 as listed [on this page in Docker hub](https://hub.docker.com/r/cimg/node/tags?page=1&name=13).
> Add minor version to executor tag

- .circleci/config.yml
Marking as semver:minor so that changes from https://github.com/CircleCI-Public/node-orb/pull/45 are properly deployed (deployment failed due to it - https://app.circleci.com/pipelines/github/CircleCI-Public/node-orb/624/workflows/efec1a76-947f-4298-8a92-63a40402eedf)
> Lock yarn version for ci/cd tests [semver:minor]

- .circleci/config.yml
- src/@orb.yml
- src/scripts/install-nvm.sh
This should be rebased, re-run (and should pass) after #72 is merged.
> Setting Node version with nvm under machine images [semver:patch]

- src/commands/install-packages.yml
I was having issues with this orb when using caching between different architectures. Including the `{{ arch }}` interpolation in the cache key
> [semver:minor] include arch in cache keys

- .circleci/config.yml
- src/commands/install-packages.yml
- src/jobs/test.yml
This adds new `pkg-manager` enum value "yarn-berry" and related changes to CI commands and cache paths.
Closes #69
> [semver:minor] Support for Yarn 2.0

- src/commands/install-packages.yml
This makes "Checking for package.json" the same as the others.
> No period at the end of heading

- .circleci/config.yml
- sample/package.json
- src/examples/node_npm_run.yml
- src/examples/node_yarn_run.yml
- src/jobs/run.yml
Adding a new job to run npm & yarn commands, similar to the node/test job.
The only way to currently utilise the multiple steps already defined in the node/test job such as:
- checkout
- install
-  install-npm/yarn 
- install-packages
and then run your own custom command such as 'npm run build' is to pass in a run-command to the node/test job defined in your workflow. 
This change allows you to make use of the all the previous steps & run your own custom npm or yarn commands such as:
```
workflows:
run-npm-command:
jobs:
- node/run:
npm-run: build
```
**Closes Issues:**
N/A
> [semver:minor] Add node/run command for npm & yarn

- src/scripts/install-nvm.sh
If there's a `.nvmrc` file in the project with the required Nodejs version, the automatic invocation of "use" will read this file, which will lead to an error, because the respective version has not been downloaded yet. Adding the `--no-use`-flag should prevent this.
> [semver:minor] Prevent nvm from running "use" on initialization

- .circleci/config.yml
- sample/other-junit.xml
- sample/package-lock.json
- sample/package.json
- sample/sum.js
- sample/sum.test.js
- sample/yarn.lock
- src/examples/jest_test_results.yml
- src/examples/test_results.yml
- src/jobs/test.yml
Two new arguments to the test job:
* test-results-path: set this to store test results if producing test reports
has been configured manually
* test-results-for: set this to jest to automatically produce and upload test
results. does need the jest-junit package installed via npm or yarn, but will
provide a helpful error message if it is not.
Tests updated to run actual jest tests.
> Support for test reports

- src/commands/install-packages.yml
When `install-packages` is invoked twice in a job, the second usage fails:
```
ln: failed to create hard link '/tmp/node-project-lockfile': File exists
```
Removing `/tmp/node-project-lockfile` and `/tmp/node-project-package.json` solves this as these links are no longer needed after the command is done running.
Installing dependencies for two different projects can be useful for running integration tests. In that case you may need deps for the app and another set of dependencies for running the integration tests.
> remove symlinks at the end: lockfile, package.json

- src/commands/install.yml
- src/scripts/install-nvm.sh
After upgrading to the latest version of the node orb we noticed that the node install command was not respecting our project's `.nvmrc` file. I've updated the install script to check for the existence of an `.nvmrc` file when the lts parameter and node version parameters are unspecified. If no `.nvmrc` file exists the latest current version of node will be used instead.
> Use .nvmrc if lts and specific node version parameters are unspecified

- src/commands/install-packages.yml
Cache key is not consistent between retrieval and saving jobs for npm - all `save_cache` steps are not respecting the `cache-only-lockfile` parameter.
**Closes Issues:**
-  #123 
-  #115
> Fix NPM Cache Keys

- src/scripts/packages/yarn-berry-install.sh
Installing YARN Packages job failed when using yarn-berry without zero installs.
#130 - the `yarn install --immutable` line is not reachable.
**Closes Issues:**
-  #130
> Fix Yarn Berry installs

- src/scripts/install-nvm.sh
Document says 
```
To install the latest LTS version, set the version to `lts`.
```
https://circleci.com/developer/ja/orbs/orb/circleci/node?version=5.0.0#commands-install
But, `node-version: lts` fails with following error.
```
Version 'lts' not found - try `nvm ls-remote` to browse available versions.
Exited with code exit status 3
```
This is causes by script does not handle `node-version: lts` well.
This PR fixes the issue.
I want to set and fix node version `lts`, but with version 5.0.0, I can't.
> Fix `lts` cannot be specified by node-version at node/install

- src/scripts/install-yarn.sh
We should check the latest version at the same source we will download from.
In this solution, we use the package.json published on https://yarnpkg.com/package/yarn to resolve the latest version.
At the time of the problem, version 1.22.18 was tagged as a release on GitHub but 1.22.17 was the latest version on yarnpkg.com. 
The error was:
```
Latest version of Yarn is 1.22.18
Checking if YARN is already installed...
A different version of Yarn is installed (1.22.17); removing it
Installing YARN v1.22.18
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat ‘yarn-v1.22.18/*’: No such file or directory
Exited with code exit status 1
CircleCI received exit code 1
```
> fix: yarn install fails when release is tagged in GitHub but not yet published on yarnpkg.com

- src/examples/npm_install.yml
If `node/install-packages` comes first, the packages will already be installed
before the correct version of npm has been installed.
It'll look something a bit like this:
```
environment:
PARAM_CACHE_PATH: ''
PARAM_OVERRIDE_COMMAND: npm install
name: Installing NPM packages
working_directory: .
- save_cache:
key: node-deps-{{ arch }}-v1-{{ .Branch }}-{{ checksum "/tmp/node-project-lockfile" }}
paths:
- ~/.npm
- run:
command: rm -f /tmp/node-project-lockfile /tmp/node-project-package.json /tmp/yarn-zero-lockfile
name: Remove temporary links
- run:
command: sudo npm install -g npm@latest
```
whereas presumably we want something like this instead:
```
- checkout
- run:
command: "# Only install nvm if it's not already installed\..."
environment:
NODE_PARAM_VERSION: '16.14'
name: Install …
```
> Swap order of steps in npm install example

- src/scripts/install-yarn.sh
The errors may be transient, and the --retry option is about re-attempting to download on a transient error.
Learn more about the retry option:
https://daniel.haxx.se/blog/2020/03/24/curl-ootw-retry-max-time/
This doesn't account for "something not gzip got downloaded, like an CDN HTML error page":
```
Selected version of Yarn is 1.22.19
Checking if YARN is already installed...
Installing YARN v1.22.19
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat 'yarn-v1.22.19/*': No such file or directory
```
> Ask curl to retry 5 times on yarn download

- .circleci/test-deploy.yml
- src/scripts/packages/determine-lockfile.sh
On windows runners, the cache keys fails to be computed because of the `checksum` function that can't find the file in /tmp. Indeed, it seems that bash `/tmp` is not the runner's `C:\tmp` directory.
See https://app.circleci.com/pipelines/github/KnodesCommunity/typedoc-plugins/693/workflows/897cb674-230e-46ae-99f5-b10d93f4b723/jobs/3872/parallel-runs/0/steps/0-106 for an example of failed step
> fix: support cache computation on windows

- src/commands/install-packages.yml
In Yarn Berry v4+, the default is to cache dependencies into a global cache (`~/.yarn/berry/cache`), as you can see here:
```shell
 docker run -it --entrypoint bash node:20
root@2d1b6b79999d:/# corepack enable
root@2d1b6b79999d:/# mkdir test-berry && cd test-berry
root@2d1b6b79999d:/test-berry# yarn init -y
yarn init v1.22.21
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
Done in 0.01s.
root@2d1b6b79999d:/test-berry# yarn set version berry
➤ YN0000: Done in 0s 13ms
root@2d1b6b79999d:/test-berry# yarn --version
4.0.2
root@2d1b6b79999d:/test-berry# yarn add semver
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + semver@npm:7.5.4, lru-cache@npm:6.0.0, yallist@npm:4.0.0
➤ …
```
> feat: support Yarn Berry global cache

- .circleci/test-deploy.yml
- sample/pnpm-lock.yaml
- src/commands/install-packages.yml
- src/commands/install-pnpm.yml
- src/commands/install.yml
- src/examples/node_pnpm_run.yml
- src/examples/pnpm_install.yml
- src/examples/run_tests_with_pnpm.yml
- src/jobs/run.yml
- src/jobs/test.yml
- src/scripts/install-pnpm.sh
- src/scripts/packages/determine-lockfile.sh
- src/scripts/packages/pnpm-install.sh
- src/scripts/run-commands-with.sh
I would assume it is just a patch or minor as it doesn't change any of defaults or the normal behaviours, just adds an optional extra feature of pnpm as a package manager.
- add support for `pnpm` as a package manager
- fix `test-deploy.yml` `node/test` and `node/run` steps to find the correct lock files for the corresponding `pkg-manager` by removing the other ones
**Closes Issues:**
- https://github.com/CircleCI-Public/node-orb/issues/167
- https://github.com/CircleCI-Public/node-orb/issues/89
Also shows how someone could do this:
- https://github.com/CircleCI-Public/node-orb/issues/194
> Feat: adding support for pnpm

- .circleci/test-deploy.yml
- src/commands/install.yml
- src/scripts/install-nvm.sh
support .node-version file
Most Node.js runtime managers support either `.nvmrc` or `.node-version` (nodenv etc...) or both (fnm, mise, asdf etc...) are supported.
However, currently only `.nvmrc` is supported.
Although it is preferable to use `.nvmrc` since we use `nvm` internally, both `.nvmrc` and `.node-version` are often in the same format.
It is possible that I am missing a specification, but I don't think it will be a problem in many cases.
https://app.circleci.com/pipelines/github/totto2727/node-orb
> feat: support .node-version file

- .circleci/test-deploy.yml
- sample/package.json
- src/jobs/test.yml
* add a parameter to upload test coverage to artifacts after running the `test` job
As recommended in the [CircleCI documentation](https://circleci.com/docs/code-coverage), uploading test coverage to artifacts is a good practice. This PR allows for uploading coverage files to artifacts by supplying the coverage path as an argument to the `test` job.
> feat: upload coverage to artifacts in test job

- .circleci/test-deploy.yml
- sample/dist/index.js
- src/jobs/run.yml
* add a parameter to upload a path to artifacts after running a script in the `run` job
Running a script often produces new files to be stored as artifacts. For example, many front-end projects use a bundler such as Webpack or Vite, and TypeScript projects need to be transpiled to JavaScript. These tools are often controlled with  a `build`, `compile` or `webpack` script.
After this step, the produced files often need to be persisted somewhere, and artifacts seems like a good place.
> feat: optionally store artifacts after script in run job

- src/commands/install.yml
`node-install-dir` isn't hooked up to anything, and appears to have never been. It's not documented (beyond automatically as a parameter) or tested. Technically a "breaking change" since it removes a parameter, but since the parameter has always been a no-op, there's no functional break (but anyone using the parameter in a config thinking it did something would get an error on updating).
> fix: remove unused node-install-dir parameter

- src/scripts/install-nvm.sh
Closes #183.
Opening a PR to get the ball rolling on this, been bit a few times now by this.
cc @KyleTryon
> fix!: do not fall back to source builds of Node.js

- .circleci/test-deploy.yml
- src/scripts/install-yarn.sh
As indicated in #212 the yarn install command fails on machine executors as the old version of yarn is not correctly uninstalled. In these machines, yarn was installed via nvm, so the binary has to be manually removed.
I'm also updating the indentation of this script file.
> Fix: reinstall a new version of yarn on machine executor

- src/commands/install-packages.yml
- src/scripts/packages/npm-install.sh
As pointed out in #202 when npm ci command is used to install dependencies, the cache is ignored. I'm adding some conditions in the command and the script to ignore the cache whenever the npm ci command is used. I'm also adding some extra descriptions in the parameters to inform the users that cache won't be used when the npm ci command is used.
> Fix: nocache npm ci

- .circleci/test-deploy.yml
- sample/package-berry.json
- sample/package.json
- src/commands/install-packages.yml
- src/scripts/packages/yarn-berry-install.sh
In the install-packages command, when setting pkg-manager to yarn-berry, it was no using yarn-berry but the old version of yarn. I'm enabling corepack in the script that installs with yarn berry, so it uses yarn-berry.
Yarn berry takes the version from package.json so this will only work when that's specified, otherwise it will use old yarn.
This is done this way to avoid setting wrong default version.
This should solve #217
> Fix: yarn berry install packages

- .circleci/test-deploy.yml
- src/commands/install.yml
There have been many reports from failures when installing an specific node version at the momento of downloading the binary. I'm adding a new parameter that allows to store the .nvm/.cache folder so the installation can use it instead of downloading every time.
> Add an option to save nvm cache on installation

- .circleci/test-deploy.yml
- src/scripts/packages/yarn-berry-install.sh
resolves #231 
Previously corepack was installed in the ~/bin as the circleci images have problems with the default directory.
I'm adding a default command to use the default location, and an alternative command to install in ~/bin when the other fails.
I'm adding a new test to validate the run on cimg image and non cimg image.
> Add alternative way to enable corepack

- .circleci/test-deploy.yml
- src/jobs/run.yml
- src/jobs/test.yml
Resolves #161 
The job run and test are using the defaults for most of the cache parameters in the install-packages command. I'm adding the parameters to these jobs as well, so they can be used with a better level of configuration.
I'm also fixing the requisites in the tests so the deploy cannot run without all the tests passing.
> Add cache parameters to jobs

- .circleci/test-deploy.yml
- src/scripts/install-yarn.sh
- src/scripts/packages/yarn-berry-install.sh
Resolves #241 
I'm adding sudo to the rm commands when overriding yarn, as it might fail without it.
> Fix sudo error overriding yarn

- .circleci/test-deploy.yml
- src/scripts/install-pnpm.sh
In some situations when the user doesn't have permissions to install global packages the installation of pnpm fails. I'm 
adding SUDO when this is required.
Resolves #251
> Fix pnpm installation
