.circleci/config.yml
src/commands/install-node.yml
src/commands/install-npm.yml
src/commands/install-yarn.yml
src/commands/install.yml

- [make sure installing node/npm/yarn works on oracle](https://discuss.circleci.com/t/convenience-images-update-add-our-convenience-image-tooling-to-your-own-docker-images-with-orbs)
- ended up improving compatibility across all platforms
- better messaging to users
- master `install` command can install node, yarn, & npm

Test against oracle

---

.circleci/config.yml
src/commands/install-yarn.yml

https://github.com/CircleCI-Public/node-orb/issues/8
some mac users are running into permission issues—`chown` the `~/.config` dir to resolve for now

Fix yarn perms

---

src/commands/install-node.yml

alpine install fails due to flimsy string manipulation
use more robust perl command to upgrade to alpine edge

[CIRCLE-19378] Use more robust upgrading-to-edge logic developed for browser tools orb

---

src/examples/npm.yml
src/examples/yarn.yml

Fixes #2.
Examples are based off of what was provided by #14.

Add Yarn and NPM examples.

---

src/commands/install-packages.yml

Just fixing a typo.
Fix typo: dependancies -> dependencies

Typo: dependancies -> dependencies [semver:patch]

---

src/examples/install_nodejs.yml

It's a typo.
fix typo in description of `install_nodejs.yml` example

[semver:patch] fix typo in description of `install_nodejs.yml` example

---

src/examples/npm_install.yml
src/examples/run_tests_with_npm.yml
src/examples/run_tests_with_yarn.yml

Fixed example config for orb inclusions as reported in #orb-registry channel.

Fixed orb import statements in examples

---

src/@orb.yml
src/commands/install-packages.yml

[semver:minor] Change default app-dir to `$CIRCLE_WORKING_DIR`

---

src/scripts/install-nvm.sh

Fixes: #62 
Brought about by @gmemstr and ARM testing.
I'm not sure about the semver level. Open to feedback.

Only install nvm when needed. [semver:patch]

---

src/commands/install-packages.yml

[semver:minor] Better handling of various lockfile options.

---

.circleci/config.yml
src/commands/install.yml
src/examples/install_nodejs.yml
src/examples/node_test_and_deploy.yml
src/examples/npm_install.yml
src/examples/run_matrix_testing.yml
src/examples/run_tests_with_npm.yml
src/examples/run_tests_with_yarn.yml
src/executors/default.yml
src/jobs/test.yml

They say its Node.js not NodeJS [semver:patch]

---

src/commands/install-packages.yml

Change the cache key pattern to allow for partial key matching. Moved `{{arch}}` to the front of the key.
This change will invalidate the user's cache

Optimize cache keys  [semver:minor]

---

src/scripts/install-nvm.sh

Set lts version as default node when set lts param [semver:patch]

---

.circleci/config.yml
.circleci/test-deploy.yml
.github/stale.yml
.yamllint
src/@orb.yml
src/commands/install-packages.yml
src/commands/install-yarn.yml
src/commands/install.yml
src/examples/install_nodejs.yml
src/examples/jest_test_results.yml
src/examples/mocha_test_results.yml
src/examples/node_npm_run.yml
src/examples/node_test_and_deploy.yml
src/examples/node_yarn_run.yml
src/examples/npm_install.yml
src/examples/run_matrix_testing.yml
src/examples/run_tests_with_npm.yml
src/examples/run_tests_with_yarn.yml
src/examples/test_results.yml
src/examples/yarn_berry_zero_install.yml
src/executors/default.yml
src/jobs/run.yml
src/jobs/test.yml
src/scripts/install-yarn.sh
src/scripts/packages/run-commands-with.sh
src/scripts/run-commands-with.sh

Orb tools 11 migration

---

src/scripts/install-nvm.sh

Motivation is to pick up this fix: https://github.com/nvm-sh/nvm/issues/2692

chore: update nvm version to v0.39.3

---

src/examples/run_matrix_testing.yml

Typo I noticed while reading the docs. 🙂

docs: fix typo

---

.circleci/test-deploy.yml

we will be deprecating older images soon

ci: change ubuntu version to default

---

.circleci/test-deploy.yml
src/commands/install-packages.yml
src/jobs/run.yml
src/jobs/test.yml

Add the requested features in #243.
I'm also using this changes to add the requested in #197.
These changes, together with the ones added in #238 will generate a new major release.

Add extra features to jobs

---

.circleci/test-deploy.yml
src/executors/default.yml

I'm updating #248 to add some tests.

Add ARM support to the executor

---

sample/package-berry.json
sample/package-lock.json
sample/package.json
sample/pnpm-lock.yaml
sample/yarn-berry.lock
sample/yarn.lock

more security updates
